# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0328eed54393c8a0e655959047c6a932c7b2fae9586e20a4c5d21114482bdcb9621718d5f9c920e462275509e8e1e69fdde35ee46090c1765c1f3d567f16f531

test:
  secret_key_base: b155637eb6e2ef97fa57306f75fc3ee0d0209cd45604678ffb6b68beb5a60fec0a829efc0b6263868ea0917e89c31b231f845347676866962dce5b9f686fb813

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
